# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 'Momangen'
email: info+website@momangen.se
adress: 'Kocksgatan 23, Stockholm, Sweden'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.momangen.se" # the base hostname & protocol for your site, e.g. http://example.com
# instagram_username: 'sethybwoy'

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: >- # this means to ignore newlines until "baseurl:"
  Galleri och Kulturförening som spiller färg, bygger skulpturer, skriver, musicerar, fotar och pysslar på Södermalm.
author:
  name: Kulturföreningen Momangen
  email: info@momangen.se 
  twitter: # twitter username without the @ symbol
#social:
#  name: Momangen
#  links:
#    - https://www.instagram.com/sethybwoy/
#    - http://www.twitter.com/heptazoid
#    - https://www.linkedin.com/in/set-hallstrom/   
lang: sv_SE

# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Plugin settings:

# Site Variables:

# # collection
collections:
  events:
    output: true
    permalink: "/events/:title/"
    future: false
  artists:
    permalink: "/artists/:title/"
    _hide_content: true
    output: false
  momangers:
    _hide_content: true
    output: false
    

#   tjanster:
#     output: "true"
#     permalink: "/tjaenster/:name/"
#   cuttlefishes:
#     output: "false"
#     _hide_content: "true"
#     _singular_name: "vi"
#     _plural_name: "vi"

# # defaults

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "*.*~", "color_chart.txt", Gemfile, Gemfile.lock]
permalink: /:categories/:year/:month/:day/:title/

timezone: Europe/Stockholm

defaults:
  - scope:
      path: "*.pdf"
    values:
      sitemap: false
  - scope:
      path: ""
    values:
      _comments:
        open: Slå på vignetten på hemsidan som visar för cyberrymden att vi har öppet
  - scope:
      path: ""
      type: "events"
    values:
      layout: "events"
      _options:
        image:
          width: 960
          height: 480
          resize_style: "cover"
          mime_type: "image/jpeg"
          uploads_dir: "images/events"
        content:
          width: 150
          height: 150
          resize_style: "cover"
          mime_type: "image/jpeg"
          uploads_dir: "images/events"
      _comments:
        title: Sidans tittle
        description: Vad som kommer stå på länken i sociala medier och sökresultat
        image: Flyer för eventet och bilden som visas på länken i sociala medier och sökresultat
        artists: Om du inte hittar artisten, måste du första skapa en profil. Du kan göra det i Explore
        event_data: Här kan du ställa in start och slut datum/tid
        category: Är det musik eller utställning?
        link: Finns det en event sida någon stans?
        date: När ska eventsidan publiceras?
  - scope:
      path: ""
      type: "artists"
    values:
      layout: "artists"
      _options:
        image: 
          width: 150
          height: 150
          resize_style: "cover"
          mime_type: "image/jpeg"
          uploads_dir: "images/artists"
      _comments:
        name: Artistnamnet
        blurb_text: Kort biografi
        nation: Var kommer artisten ifrån (gärna förkortning)
        link: Länk till artistens hemsida
        image: bild på artisten (om det finns ett ansikte, se till att det är i mitten av bilden)
  - scope:
      path: ""
      type: "momangers"
    values:
      _options:
        image: 
          width: 150
          height: 150
          resize_style: "cover"
          mime_type: "image/jpeg"
          uploads_dir: "images/momangers"
      _comments:
        namn: Artistnamnet
        blurb_text: Kort biografi
        nation: Var kommer artisten ifrån (gärna förkortning)
        link: Länk till artistens hemsida
        image: bild på artisten (om det finns ett ansikte, se till att det är i mitten av bilden)

#   - scope:
#       path: ""
#       type: "posts"
#     values:
#       layout: "tjaenster"
#       permalink: /:year/:month/:day/:title/
#       _options:
#         image:
#           uploads_dir: "images/tjaenster"
#           width: "1280"
#           height: "550"
#           resize_style: "cover"
#           mime_type: "image/jpeg"
#         content:
#           uploads_dir: "images/tjaenster"
#           width: "1280"
#           height: "550"
#           resize_style: "cover"
#           mime_type: "image/jpeg"
#   - scope:
#       path: ""
#       type: "cuttlefishes"
#     values:
#       _options:
#         image:
#           uploads_dir: "images"
#           width: "120"
#           height: "120"
#           resize_style: "cover"
#         content:
#           uploads_dir: "images"
#           width: "120"
#           height: "120"
#           resize_style: "cover"

categories:
  - ljudkonst
  - bildkonst
  - gatukonst
  - graffiti
  - bokförläggning
  - performance
  - release